### ISSUE TITLE
ENH Support of background tasks

### ISSUE THREAD

**Issue by Hollander-1908** [Miksus/rocketry#121] opened 2022-09-27 22:00 UTC
**Is your feature request related to a problem? Please describe.**
It seems not possible to run tasks in the background. 

**Describe the solution you'd like**
I would like to run the tasks in the background so it can do other stuff in the meantime. 

**Describe alternatives you've considered**
I use APScheduler right now but besides it supports background tasks I feel like Rocketry would be way more convenient if it supports this feature.

**Comment by Miksus** [comment] 2022-09-28 05:22
Do you mean that to run a (Rocketry) task permanently alongside the rest of the scheduler? If so, Rocketry indeed fully supports it using ``permanent_task``. Possibly not well documented yet.

```python
@app.task(on_startup=True, permanent_task=True, execution="async")
async def do_background():
    while True:
        ...
```

The ``permanent_task=True`` is nothing super special. It just means that the task cannot be timeouted and when the scheduler shuts down, the engine will not wait for it to finish and it will terminate it outright. It supports all of the execution methods.

Or did you mean something else?

**Comment by Hollander-1908** [comment] 2022-09-28 14:57
Actually it should be the other way around like APScheduler is doing with their `BackgroundScheduler()`. 

So the scheduler should be in the background. Not other tasks. I tried above method but it doesn't seem to start my web app, it's just hanging.

**Comment by Miksus** [comment] 2022-09-28 15:45
Rocketry's scheduler does not make assumptions on which application runs on top of it. It's the responsibility of the main application to inform Rocketry's scheduler to quit scheduling. You can use the ``shut_cond`` or the ``shut_down`` method. There are various ways to signal for exit and Rocketry should not make assumptions regarding this or force you to use specific one.

Perhaps there could be a collection of conditions for most common kill signals but it should be easy to create your own condition and add that as a ``shut_cond``.

I can later elaborate a bit more (on phone). What technologies are you using for the web app?

If you embed your web app to Rocketry's task, you probably need to do the reverse: ask the web app to exit from the Rocketry task. And it depends on the web library how its shutdown mechanism works.

**Comment by Miksus** [comment] 2022-10-02 07:39
Without further information, I'll close this issue.

Feel free to open another one if this was not solved but include the web technology that was used so we can see whether the issue is in Rocketry or in the web technology (like does it support adding callbacks for shutdown sequence). 

By design Rocketry is well suitable to be embedded in other applications. I have demonstrated it with FastAPI: https://github.com/Miksus/rocketry-with-fastapi

**Closed by Miksus** 2022-10-02 07:39 UTC
Labels: enhancement
